appender.0.type = Console
appender.0.name = CONSOLE_LOG
appender.0.layout.type = PatternLayout
appender.0.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

appender.1.type = RollingFile
appender.1.name = ROLLING_LOG
appender.1.fileName = ${sys:user.home}/.idrop/idrop.log
appender.1.filePattern = ${sys:user.home}/.idrop/idrop.log.%i.gz
appender.1.strategy.type = DefaultRolloverStrategy
appender.1.strategy.max = 9
appender.1.policy.type = Policies
appender.1.policy.0.type = OnStartupTriggeringPolicy
appender.1.policy.1.type = SizeBasedTriggeringPolicy
appender.1.policy.1.size = 100k
appender.1.layout.type = PatternLayout
appender.1.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

rootLogger.level = INFO
rootLogger.appenderRef.0.ref = CONSOLE_LOG
rootLogger.appenderRef.0.level = WARN
rootLogger.appenderRef.1.ref = ROLLING_LOG
rootLogger.appenderRef.1.level = INFO

## custom levels copied from log4j v1
logger.11.name=org.irods.jargon.core
logger.11.level=INFO
logger.12.name=org.irods.jargon.conveyor
logger.12.level=INFO
logger.13.name=org.irods.jargon.usertagging
logger.13.level=ERROR
logger.14.name=org.irods.jargon.datautils
logger.14.level=INFO

## filter out the noise from hibernate and spring
logger.90.name=org.hibernate
logger.90.level=ERROR
logger.91.name=org.springframework
logger.91.level=ERROR